image: python:3.8

pipelines:
  default:
    - step:
        name: Setup
        caches:
          - pip
        script:
          - if [ -f requirements_ci.txt ]; then pip install -r requirements_ci.txt; fi
    - parallel:
      - step:
          name: Lint code
          script:
            - flake8 cardwirth.py cw
      - step:
          name: Lint types
          script:
            - mypy cardwirth.py
