image: python:3.8

pipelines:
  default:
    - step:
        name: Lint code and type hints
        caches:
          - pip
        script:
          - if [ -f requirements_ci.txt ]; then pip install -r requirements_ci.txt; fi
          - flake8 cardwirth.py cw
          - mypy cardwirth.py
